# Borrowed starter Circle config for setting up ios/android react-native CI.
# https://github.com/CircleCI-Public/circleci-demo-react-native/blob/master/.circleci/config.yml
version: 2
jobs:
  build_and_test:
    working_directory: ~/raha-mobile-app
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
      - run: yarn install
      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
      - run:
          name: tests
          command: |
            yarn config:dev:test
            mkdir -p test-results/jest
            yarn run test
          environment:
            JEST_JUNIT_OUTPUT: test-results/jest/junit.xml
      - persist_to_workspace:
          root: ~/raha-mobile-app
          paths:
            - node_modules
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
  # Builds and publishes the Android prod APK off of master branch to Google
  # Play Alpha track
  publish_android_alpha:
    working_directory: ~/raha-mobile-app/android
    docker:
      - image: circleci/android:api-26-node8-alpha
    steps:
      # - checkout:
      #     path: ~/raha-mobile-app
      # - attach_workspace:
      #     at: ~/raha-mobile-app
      # - restore_cache:
      #     key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}
      - run: yarn config:deploy && yarn bumpVersion -r internal --apply && ./gradlew publishProdRelease

  # android:
  #   working_directory: ~/raha-mobile-app/android
  #   docker:
  #     - image: circleci/android:api-27-node8-alpha
  #   steps:
  #     - checkout:
  #         path: ~/raha-mobile-app
  #     - attach_workspace:
  #         at: ~/raha-mobile-app
  #     - restore_cache:
  #         key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}
  #     - run: bundle install
  #     - save_cache:
  #         key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}
  #         paths:
  #           - vendor/bundle
  #     - run:
  #         name: fastlane tests
  #         command: |
  #           mkdir -p test-results/fastlane
  #           bundle exec fastlane test
  #           mv fastlane/report.xml test-results/fastlane
  #     - store_test_results:
  #         path: test-results
  #     - store_artifacts:
  #         path: test-results
  # ios:
  #   macos:
  #     xcode: "9.0"
  #   working_directory: ~/raha-mobile-app
  #   # use a --login shell so our "set Ruby version" command gets picked up for later steps
  #   shell: /bin/bash --login -o pipefail
  #   steps:
  #     - checkout
  #     - run:
  #         name: set Ruby version
  #         command:  echo "ruby-2.4" > ~/.ruby-version
  #     - restore_cache:
  #         key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
  #     - restore_cache:
  #         key: node-v1-{{ checksum "package.json" }}-{{ arch }}
  #     # not using a workspace here as Node and Yarn versions
  #     # differ between our macOS executor image and the Docker containers above
  #     - run: yarn install
  #     - save_cache:
  #         key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
  #         paths:
  #           - ~/.cache/yarn
  #     - save_cache:
  #         key: node-v1-{{ checksum "package.json" }}-{{ arch }}
  #         paths:
  #           - node_modules
  #     - restore_cache:
  #         key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}
  #     - run:
  #         command: bundle install
  #         working_directory: ios
  #     - save_cache:
  #         key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}
  #         paths:
  #           - vendor/bundle
  #     - run:
  #         command: bundle exec fastlane test
  #         working_directory: ios
  #     - run:
  #         name: set up test results
  #         working_directory: ios
  #         when: always
  #         command: |
  #           mkdir -p test-results/fastlane test-results/xcode
  #           mv fastlane/report.xml test-results/fastlane
  #           mv fastlane/test_output/report.junit test-results/xcode/junit.xml
  #     - store_test_results:
  #         path: ios/test-results
  #     - store_artifacts:
  #         path: ios/test-results

workflows:
  version: 2
  commit:
    jobs:
      - build_and_test
      - publish_android_alpha:
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - master
                - tina/upload_apk
